config/routes.rb
Wiseguide::Application.routes.draw do
  resources :counties

  resources :trip_reasons

  resources :routes

  resources :referral_types

  resources :impairments

  resources :funding_sources

  resources :event_types

  resources :ethnicities

  resources :dispositions

  resources :customer_support_network_members
  
  resources :customer_impairments, :except => [:index, :show]

  resources :customers do
    collection do
      get  :search
    end
    
    member do
      get :download_original_portrait
      get :download_small_portrait
    end
  end

  resources :kases, :path => "cases" do 
    post "add_route", :on=>:collection
    post "delete_route", :on=>:collection
  end

  resources :contacts

  resources :events

  #these are called "assessments" in user-visible text
  resources :surveys, :controller=>'Surveyor' do
    delete "/:survey_code/:response_set_code/delete", :to => "surveyor#delete_response_set", :as=>:delete, :on=>:collection
    get "new_survey", :on=>:collection
    put "new_survey", :on=>:collection, :to=>"surveyor#create_survey", :as=>:new_survey
    post "reactivate_survey", :to=>"surveyor#reactivate", :as=>:reactivate
  end

  resources :outcomes

  devise_for :users, :controllers=>{:sessions=>"users"} do
    get "new_user" => "users#new_user"
    post "create_user" => "users#create_user"
    put "create_user" => "users#create_user"
    get "init" => "users#show_init"
    post "logout" => "users#sign_out"
    post "init" => "users#init"
    post "update_user" => "users#update"
    delete "user" => "users#delete"
    get "show_change_password" => "users#show_change_password"
    match "change_password"  => "users#change_password"

  end

  match 'users', :controller=>:admin, :action=>:users
  match 'admin', :controller=>:admin, :action=>:index
  match 'reports', :controller=>:reports, :action=>:index

  match 'reports(/:action)', :controller=>:reports

  match "test_exception_notification" => "application#test_exception_notification"

  root :to => "home#index"
end

app/views/admin/index.html.erb
<%= link_to "Counties", counties_path %><br/>
<%= link_to "Dispositions", dispositions_path %><br/>
<%= link_to "Ethnicities", ethnicities_path %><br/>
<%= link_to "Event Types", event_types_path %><br/>
<%= link_to "Funding Sources", funding_sources_path %><br/>
<%= link_to "Impairments", impairments_path %><br/>
<%= link_to "Referral Types", referral_types_path %><br/>
<%= link_to "Routes", routes_path %><br/>
<%= link_to "Trip Reasons", trip_reasons_path %><br/>
<%= link_to "Users", users_path %><br/>
<%= link_to "Surveys", surveys_path %><br/>

app/views/admin/users.html.erb
<% if @users == 0 %>
  <p>No users yet.</p>
<% else %>
  <table>
    <tr>
      <th>Email</th>
      <th>Role</th>
      <th>Last login</th>
      <% if can? :edit, User %>
      <th></th>
      <th></th>
      <% end %>
    </tr>

    <% for user in @users %>
    <tr>
      <td class="<%= user.role_name.downcase %>">
        <%= user.email %>
        <% if user == current_user %>
          <span class="separator">|</span> <%= link_to "Change Password", show_change_password_path, :class=>'change-password' %>
        <% end %>
      </td>
      <td><%= user.role_name %></td>
      <td><%= user.last_sign_in_at %></td>
      <% if can? :edit, user %>
      <td>
        <%= form_for(user, :url=>update_user_path(:id=>user.id), :html => { :method => :post }) do |f| %>
          <%= f.select(:level, user_roles(user.level)) %>
          <%= f.submit "Change role" %>
        <% end %>
      </td>
      <td>
        <%= button_to("Delete", user_path(:id=>user.id), :confirm => 'Are you sure?', :class=>'delete', :method=>:delete) unless user.level == -1 %>
      </td>
      <% end %>
    </tr>
    <% end %>
 </table>
<% end %>

<% if can? :edit, User %>
<hr/>
<%= link_to "New User", new_user_path, :class => "new-user action-bttn" %>
<% end %>