config/routes.rb
Wiseguide::Application.routes.draw do
  resources :counties

  resources :trip_reasons

  resources :routes

  resources :referral_types

  resources :impairments

  resources :funding_sources

  resources :event_types

  resources :ethnicities

  resources :dispositions

  resources :customer_support_network_members
  
  resources :customer_impairments, :except => [:index, :show]

  resources :customers do
    collection do
      get  :search
    end
    
    member do
      get :download_original_portrait
      get :download_small_portrait
    end
  end

  resources :kases, :path => "cases" do 
    post "add_route", :on=>:collection
    post "delete_route", :on=>:collection
  end

  resources :contacts

  resources :events

  #these are called "assessments" in user-visible text
  resources :surveys, :controller=>'Surveyor' do
    delete "/:survey_code/:response_set_code/delete", :to => "surveyor#delete_response_set", :as=>:delete, :on=>:collection
    get "new_survey", :on=>:collection
    put "new_survey", :on=>:collection, :to=>"surveyor#create_survey", :as=>:new_survey
    post "reactivate_survey", :to=>"surveyor#reactivate", :as=>:reactivate
  end

  resources :outcomes

  devise_for :users, :controllers=>{:sessions=>"users"} do
    get "new_user" => "users#new_user"
    post "create_user" => "users#create_user"
    put "create_user" => "users#create_user"
    get "init" => "users#show_init"
    post "logout" => "users#sign_out"
    post "init" => "users#init"
    post "update_user" => "users#update"
    delete "user" => "users#delete"
    get "show_change_password" => "users#show_change_password"
    match "change_password"  => "users#change_password"

  end

  match 'users', :controller=>:admin, :action=>:users
  match 'admin', :controller=>:admin, :action=>:index
  match 'reports', :controller=>:reports, :action=>:index

  match 'reports(/:action)', :controller=>:reports

  match "test_exception_notification" => "application#test_exception_notification"

  root :to => "home#index"
end

app/views/cases/_assessments.html.erb
<h1>Assessments</h1>
<table>
<% for assessment in @case.assessments %>
<tr>
<td><%= @assessment.created_at %></td>
<td>TODO: surveys</td>
<td><%= link_to :details, @assessment %></td>
</tr>
<% end %>
</table>
<% if can? :edit, @case %>
<%= link_to "Add", new_assessment_path(:case_id=>@case.id) %>
<% end %>

app/views/cases/_contacts.html.erb
<h1>Contacts</h1>

<table>
<% for contact in @case.contacts %>
<tr>
  <td><%= contact.date_time.date %></td>
  <td><%= contact.method %></td>
  <td><%= contact.description %></td>
  <td><%= link_to "Details", contact %></td>
</tr>
<% end %> 
</table>
<% if can? :edit, @case %>
<%= link_to "Add", new_contact_path(:case_id=>@case.id) %>
<% end %>

app/views/cases/_events.html.erb
<h1>Training Events</h1>

<table>
<% for event in @case.events %>
<tr>
  <td><%= event.date_time.date %></td>
  <td><%= event.event_type.name %></td>
  <td><%= event.user.email %></td>
  <td><%= link_to "Details", event %></td>
</tr>
<% end %> 
</table>
<% if can? :edit, @case %>
<%= link_to "Add", new_event_path(:case_id=>@case.id) %>
<% end %>

app/views/cases/_form.html.erb
<h1><%= @case.customer.name %></h1>

<%= form_for @case do |f| %>
  <% if @case.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@case.errors.count, "error") %> prohibited this case from being saved:</h2>

      <ul>
      <% @case.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= f.hidden_field :customer_id %>

<%= f.label :open_date, "Opened" %><br/>
<%= f.text_field :open_date %><br/>


<%= f.label :referral_source %><br/>
<%= f.text_field :referral_source %><br/>

<%= f.label :referral_type_id, "Referral Source Type" %><br/>

<%= f.collection_select :referral_type_id, @referral_types, :id, :name %><br/>

<%= f.label :user_id, "Assigned to" %><br/>
<%= f.collection_select :user_id, @users, :id, :email %><br/>

<%= f.label :funding_source_id, "Default funding source" %><br/>
<%= f.collection_select :funding_source_id, @funding_sources, :id, :name %><br/>

<%= f.label :close_date, "Closed" %><br/>
<%= f.text_field :close_date %><br/>

<%= f.label :disposition_id, "Disposition" %><br/>
<%= f.collection_select :disposition_id, @dispositions, :id, :name %><br/>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

<%= render "contacts" %>

<%= render "events" %>

<%= render "assessments" %>

<%= render "routes", :locals=>{:edit => true} %>

<%= render "outcomes" %>

app/views/cases/_outcomes.html.erb
<h1>Outcomes</h1>

<% for outcome in @case.outcomes %>
<h2><%= outcome.trip_reason.name %></h2><% if can :edit, outcome %>
<%= link_to "Edit", outcome %>
<% end %>
<table>
<tr>
<th>When</th>
<th>Trips/wk</th>
<th>VMR</th>
</tr>

<tr>
<td>Exit</td>
<td><%= outcome.exit_trip_count %></td>
<td><%= outcome.exit_vehicle_miles_reduced %></td>
</tr>

<tr>
<td>3 Months</td>
<% if outcome.three_month_unreachable %>
<td colspan="2">not reachable</td>
<% else %>
<td><%= outcome.three_month_trip_count %></td>
<td><%= outcome.three_month_vehicle_miles_reduced %></td>
<% end %>
</tr>

<tr>
<td>6 Months</td>
<% if outcome.six_month_unreachable %>
<td colspan="2">not reachable</td>
<% else %>
<td><%= outcome.six_month_trip_count %></td>
<td><%= outcome.six_month_vehicle_miles_reduced %></td>
<% end %>
</tr>

</table>
<% end %>

<% if can? :edit, @case %>
<%= link_to "Add", new_outcome_path(:case_id=>@case.id) %>
<% end %>

app/views/cases/_routes.html.erb
<h1>Routes Trained</h1>
<table id="routes">
<% for route in @case.routes %>
<%= render :partial=>"route_row", :locals=>{:route=>route, :kase=>@case, :edit=>true} %>
<% end %>
</table>

<% if can? :edit, @case %>
<%= link_to "Add [TODO: make this link show this form]" %>

<%= form_for @case_route, :url=>add_route_cases_path, :html=>{:remote=>:true, :id=>"new_route_form", :method=>:post, "data-type"=>:html} do |f| %>
  <%= f.hidden_field :case_id %>
  <%= f.collection_select :route_id, @routes, :id, :name %>
  <%= f.submit %>
<% end %>
<% end %>

<script type='text/javascript'>
function init_row(index, row) {
    $(row).bind('ajax:success', function(evt, data, status, xhr){
        var $this = $(this);
        $('#case_route_' + data.case_id + "_" + data.route_id).remove();
    })
}
$('.case_route_row').each (init_row);

$('#new_route_form')
  .bind('ajax:success', function(evt, data, status, xhr){
    var $this = $(this);

    $('#routes').append(xhr.responseText);

    init_row(null, '#routes tbody tr:last');

    $this.find('.errors').empty();

  })
  .bind('ajax:error', function(evt, xhr, status, error){

    // Display the errors (i.e. an error partial or helper)
    $(this).find('.errors').html(xhr.responseText);

  });
</script>

app/views/cases/edit.html.erb
<%= render "form" %>