config/routes.rb
Wiseguide::Application.routes.draw do
  resources :counties

  resources :trip_reasons

  resources :routes

  resources :referral_types

  resources :impairments

  resources :funding_sources

  resources :event_types

  resources :ethnicities

  resources :dispositions

  resources :customer_support_network_members
  
  resources :customer_impairments, :except => [:index, :show]

  resources :customers do
    collection do
      get  :search
    end
    
    member do
      get :download_original_portrait
      get :download_small_portrait
    end
  end

  resources :kases, :path => "cases" do 
    post "add_route", :on=>:collection
    post "delete_route", :on=>:collection
  end

  resources :contacts

  resources :events

  #these are called "assessments" in user-visible text
  resources :surveys, :controller=>'Surveyor' do
    delete "/:survey_code/:response_set_code/delete", :to => "surveyor#delete_response_set", :as=>:delete, :on=>:collection
    get "new_survey", :on=>:collection
    put "new_survey", :on=>:collection, :to=>"surveyor#create_survey", :as=>:new_survey
    post "reactivate_survey", :to=>"surveyor#reactivate", :as=>:reactivate
  end

  resources :outcomes

  devise_for :users, :controllers=>{:sessions=>"users"} do
    get "new_user" => "users#new_user"
    post "create_user" => "users#create_user"
    put "create_user" => "users#create_user"
    get "init" => "users#show_init"
    post "logout" => "users#sign_out"
    post "init" => "users#init"
    post "update_user" => "users#update"
    delete "user" => "users#delete"
    get "show_change_password" => "users#show_change_password"
    match "change_password"  => "users#change_password"

  end

  match 'users', :controller=>:admin, :action=>:users
  match 'admin', :controller=>:admin, :action=>:index
  match 'reports', :controller=>:reports, :action=>:index

  match 'reports(/:action)', :controller=>:reports

  match "test_exception_notification" => "application#test_exception_notification"

  root :to => "home#index"
end

app/models/funding_source.rb
class FundingSource < ActiveRecord::Base
  stampable :creator_attribute => :created_by_id, :updater_attribute => :updated_by_id
  belongs_to :created_by, :foreign_key => :created_by_id, :class_name=>'User'
  belongs_to :updated_by, :foreign_key => :updated_by_id, :class_name=>'User'

end

app/controllers/funding_sources_controller.rb
class FundingSourcesController < ApplicationController
  load_and_authorize_resource
  # GET /funding_sources
  # GET /funding_sources.xml
  def index
    @funding_sources = FundingSource.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @funding_sources }
    end
  end

  # GET /funding_sources/1
  # GET /funding_sources/1.xml
  def show
    @funding_source = FundingSource.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @funding_source }
    end
  end

  # GET /funding_sources/new
  # GET /funding_sources/new.xml
  def new
    @funding_source = FundingSource.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @funding_source }
    end
  end

  # GET /funding_sources/1/edit
  def edit
    @funding_source = FundingSource.find(params[:id])
  end

  # POST /funding_sources
  # POST /funding_sources.xml
  def create
    @funding_source = FundingSource.new(params[:funding_source])

    respond_to do |format|
      if @funding_source.save
        format.html { redirect_to(@funding_source, :notice => 'Funding source was successfully created.') }
        format.xml  { render :xml => @funding_source, :status => :created, :location => @funding_source }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @funding_source.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /funding_sources/1
  # PUT /funding_sources/1.xml
  def update
    @funding_source = FundingSource.find(params[:id])

    respond_to do |format|
      if @funding_source.update_attributes(params[:funding_source])
        format.html { redirect_to(@funding_source, :notice => 'Funding source was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @funding_source.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /funding_sources/1
  # DELETE /funding_sources/1.xml
  def destroy
    @funding_source = FundingSource.find(params[:id])
    @funding_source.destroy

    respond_to do |format|
      format.html { redirect_to(funding_sources_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/funding_sources_helper.rb
module FundingSourcesHelper
end

app/views/funding_sources/_form.html.erb
<%= form_for(@funding_source) do |f| %>
  <% if @funding_source.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@funding_source.errors.count, "error") %> prohibited this funding_source from being saved:</h2>

      <ul>
      <% @funding_source.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/funding_sources/edit.html.erb
<h1>Editing funding source</h1>

<%= render 'form' %>

<%= link_to 'Show', @funding_source %> |
<%= link_to 'Back', funding_sources_path %>

app/views/funding_sources/index.html.erb
<h1>Listing funding sources</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @funding_sources.each do |funding_source| %>
  <tr>
    <td><%= funding_source.name %></td>
    <td><%= link_to 'Show', funding_source %></td>
    <td><%= link_to 'Edit', edit_funding_source_path(funding_source) %></td>
    <td><%= link_to 'Destroy', funding_source, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Funding source', new_funding_source_path %>

app/views/funding_sources/new.html.erb
<h1>New funding source</h1>

<%= render 'form' %>

<%= link_to 'Back', funding_sources_path %>

app/views/funding_sources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @funding_source.name %>
</p>


<%= link_to 'Edit', edit_funding_source_path(@funding_source) %> |
<%= link_to 'Back', funding_sources_path %>